### ISSUE TITLE
Make embeds scrollable by everyone by default

### ISSUE THREAD

**Issue by sinus-x** [pumpkin-py/pumpkin-py#203]
Currently, only the current user can scroll the ScrollableEmbed. However, that is annonying sometimes, it would be nice if that was optional.

Since we are already using buttons, we can add another one to act as lock-unlock. When clicked by the original author, it will be toggled on and off.

 When lock is on, only the original author can scroll through, which is the current behavior. When the lock is off, anyone can scroll through.
 
 IMO the default should be unlocked, but the developer may choose that some functionality should be locked to the author. I'm not sure if it is possible to dynamically change the buttons (e.g. color it red if it's locked, or change the emoji to flip between :lock: and :unlock:).

**Comment by ArcasCZ** [comment]
Buttons can be dynamically changed, but they must be created manually (not using decorator).

**Comment by sinus-x** [comment]
Implemented in PR #205
