### ISSUE TITLE
Discussion Channel or Discord?

### ISSUE THREAD

**Issue by azcoigreach** [pumpkin-py/pumpkin-py#307]
Would it be possible to activate the Discussions section of this Git or do you have a Discord where we can chat and collaborate??

I have a ton of questions. Thanks.  AZ

**Comment by sinus-x** [comment]
Yeah, until recently we haven't had any external users, so we are on our Discord sever.

You can join https://discord.gg/vutfekt and after passing the verification look into #add-roles channel for **bot-dev** role.
