### ISSUE TITLE
DM handler

### ISSUE THREAD

**Issue by sinus-x** [pumpkin-py/pumpkin-py#77]
Add new DM handler to `utils.py` which will handle 403 Forbidden exceptions.

```py
await send_dm(user: Union[discord.Member, discord.User], text: str, embed: Optional[discord.Embed] = None) -> bool:
   """Try to send message.
   
   ...
   :return: ``True`` if the  action was succesfull, ``False`` otherwise.
   """
```

Some users have DMs disabled, and this causes exceptions to be thrown.

Tip: Use [contextlib](https://docs.python.org/3/library/contextlib.html).

**Comment by supercalifragilistic01** [comment]
#keep_learning

**Comment by sinus-x** [comment]
@Czechbol We should be checking if the commit message contains the `Resolves:` keyword, so the issues aren't left unclosed.

@supercalifragilistic01 Thanks for interesting addition to the conversation.
